server {
    listen 80;
    server_name tools.steffenebert.codes www.tools.steffenebert.codes;

    # Certbot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # If certs exist, redirect to HTTPS. Otherwise serve content over HTTP.
    location / {
        # This block serves content over HTTP.
        # After certs are provisioned, the ssl server block below handles traffic
        # and this block only handles the HTTPS redirect.
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name tools.steffenebert.codes www.tools.steffenebert.codes;

    ssl_certificate /etc/letsencrypt/live/tools.steffenebert.codes/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/tools.steffenebert.codes/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
