server {
    listen 80;
    server_name tools.steffenebert.codes www.tools.steffenebert.codes;

    # Certbot challenge
    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    # Serve site over HTTP until certs are ready
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
